---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'postfix'
    - 'ksm-control-daemon'
    - 'open-iscsi'
    - 'proxmox-ve'
    - 'patch'

- name: apply patch
  patch:
    src: 'pvemanagerlib.js.diff'
    dest: '/usr/share/pve-manager/ext6/pvemanagerlib.js'

- name: rm deb list
  file:
    state: absent
    path: '/etc/apt/sources.list.d/pve-enterprise.list'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
