---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'postfix'
    - 'ksm-control-daemon'
    - 'open-iscsi'
    - 'proxmox-ve'
    - 'patch'

- name: apply patch
  patch:
    src: 'pvemanagerlib.js.diff'
    dest: '/usr/share/pve-manager/ext4/pvemanagerlib.js'



## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
