---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'postfix'
    - 'ksm-control-daemon'
    - 'open-iscsi'
    - 'proxmox-ve'
    - 'patch'

- name: install pip proxmoxer
  pip:
    name: "proxmoxer"

- name: copy patch
  copy:
    src: 'pvemanagerlib.js.diff'
    dest: '/usr/share/pve-manager/js/pvemanagerlib.js.diff'

- name: add cron job
  cron:
    name:   '{{ item.name }}'
    minute: '{{ item.minute | default("*")}}'
    hour:   '{{ item.hour | default("*")}}'
    user:   '{{ item.user }}'
    job:    '{{ item.job }}'
  with_items:
    - {name: 'proxmox patch', minute: '10' ,hour: '0', user: 'root', job: "patch -p < /usr/share/pve-manager/js/pvemanagerlib.js.diff" }

- name: apply patch
  patch:
    src: 'pvemanagerlib.js.diff'
    dest: '/usr/share/pve-manager/js/pvemanagerlib.js'

- name: rm deb list
  file:
    state: absent
    path: '/etc/apt/sources.list.d/pve-enterprise.list'

- name: copy cron.hourly cleaning_of_old_backups_of_virtual_machines
  template:
    src: "etc/cron.hourly/cleaning_of_old_backups_of_virtual_machines.j2"
    dest: '/etc/cron.hourly/cleaning_of_old_backups_of_virtual_machines'
    owner: 'root'
    group: 'root'
    mode: '0711'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
